import Head from "next/head";
import { Roboto } from "next/font/google";
import dynamic from 'next/dynamic'



const NoSSRAuth = dynamic(() => import('../components/auth/auth'), { ssr: false })

export default function Home() {

  return (
    <>
      <Head>
        <title>Solar Data - Sun is Power</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/solar-data-colored-logo.png" />
      </Head>
      <NoSSRAuth />
    </>
  );
}
